/// Generate a hook script for the given event
pub fn generate_hook_script(event: &str) -> String {
    format!(
        r#"#!/bin/sh
# Generated by gitclaude - do not edit manually

# Check if gitclaude is installed
if ! command -v gitclaude &> /dev/null; then
    echo "gitclaude not found, skipping hook"
    exit 0
fi

# Run gitclaude for this event
gitclaude run {event} "$@"
"#,
        event = event
    )
}

/// Generate a blocking hook script (for pre-commit)
pub fn generate_blocking_hook_script(event: &str) -> String {
    format!(
        r#"#!/bin/sh
# Generated by gitclaude - do not edit manually

# Check if gitclaude is installed
if ! command -v gitclaude &> /dev/null; then
    echo "gitclaude not found, skipping hook"
    exit 0
fi

# Run gitclaude for this event (blocking mode)
gitclaude run {event} --blocking "$@"
exit_code=$?

if [ $exit_code -ne 0 ]; then
    echo "gitclaude validation failed"
    exit 1
fi

exit 0
"#,
        event = event
    )
}
